### ISSUE TITLE
Is pretrained model available?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [sanyam5/irlc-vqa#1]
Hi Sanyam,

Thanks for your nice work! I wonder could you upload a pretrained model? Since the training process needs too large data and too many time :)

Best,
Zhihao

**Comment by sanyam5** [comment]
Hi @ZHAOZHIHAO, unfortunately, I do not have a pre-trained model. You will need to train it from scratch. Also, I am not sure of the legal issues around hosting a pre-trained model.
